# Generated by Django 2.1.2 on 2019-05-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_text', models.CharField(max_length=200)),
                ('floors', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss_text', models.CharField(max_length=200)),
                ('floor_date', models.DateTimeField(verbose_name='date published')),
                ('motto_text', models.CharField(max_length=200)),
                ('bunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torch.Bunch')),
            ],
        ),
    ]
