# Generated by Django 2.1.2 on 2019-05-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torch', '0002_auto_20190515_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('chinese1', models.CharField(max_length=32)),
                ('chinese2', models.CharField(max_length=32)),
                ('chinese3', models.CharField(max_length=32)),
                ('chinese4', models.CharField(max_length=32)),
                ('example', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Wordclass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='wordclass1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordclass1', to='torch.Wordclass'),
        ),
        migrations.AddField(
            model_name='word',
            name='wordclass2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordclass2', to='torch.Wordclass'),
        ),
        migrations.AddField(
            model_name='word',
            name='wordclass3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordclass3', to='torch.Wordclass'),
        ),
        migrations.AddField(
            model_name='word',
            name='wordclass4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordclass4', to='torch.Wordclass'),
        ),
    ]
